// generated by unplugin-vue-components
// We suggest you to commit this file into source control
// Read more: https://github.com/vuejs/vue-next/pull/3399

declare module 'vue' {
  export interface GlobalComponents {
    AboutPage: typeof import('./src/components/AboutPage.vue')['default']
    ContactPage: typeof import('./src/components/ContactPage.vue')['default']
    Footer: typeof import('./src/components/Footer.vue')['default']
    HeroPage: typeof import('./src/components/heroPage.vue')['default']
    Navbar: typeof import('./src/components/Navbar.vue')['default']
    ProjectCard: typeof import('./src/components/ProjectCard.vue')['default']
    ProjectPage: typeof import('./src/components/ProjectPage.vue')['default']
    ScrollButton: typeof import('./src/components/ScrollButton.vue')['default']
  }
}

export { }
